PeerOrgs:
  - Name: AuditorOrg
    Domain: auditor.rec.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 127.0.0.1
        - peer0.auditor.rec.com
    Users:
      Count: 1
